use bls12_381::{G1Projective, G2Projective, Scalar};
use ff::Field;
use group::{Curve, Group};
use rand::rngs::OsRng;
use std::collections::HashMap;

/// Represents a single node's share in the FROST/Threshold scheme
#[derive(Clone)]
pub struct FrostKeyShare {
    pub node_id: u32,
    pub secret_share: Scalar,
    pub public_key: G2Projective,
    pub verification_keys: HashMap<u32, G2Projective>,
}

/// A signature share generated by a single node
#[derive(Clone)]
pub struct SignatureShare {
    pub node_id: u32,
    pub share: G1Projective,
}

pub struct Frost;

impl Frost {
    /// Simulates a Trusted Dealer for DKG (Distributed Key Generation)
    /// In a fully decentralized setup, this would be replaced by a proper DKG protocol.
    pub fn trusted_dealer(
        threshold: usize,
        total_nodes: usize,
    ) -> (G2Projective, HashMap<u32, FrostKeyShare>) {
        let mut rng = OsRng;

        // Generate polynomial coefficients: f(x) = a_0 + a_1*x + ... + a_{t-1}*x^{t-1}
        let mut coeffs = Vec::with_capacity(threshold);
        for _ in 0..threshold {
            coeffs.push(Scalar::random(&mut rng));
        }

        let group_secret = coeffs[0];
        let group_public = G2Projective::generator() * group_secret;

        let mut verification_keys = HashMap::new();
        let mut secret_shares = HashMap::new();

        for i in 0..total_nodes as u32 {
            let x = Scalar::from((i + 1) as u64); // x-coordinate cannot be 0
            let mut share = Scalar::zero();
            let mut x_pow = Scalar::one();

            for coeff in &coeffs {
                share += coeff * &x_pow;
                x_pow *= x;
            }

            let pk = G2Projective::generator() * share;
            verification_keys.insert(i, pk);
            secret_shares.insert(i, share);
        }

        let mut key_shares = HashMap::new();
        for i in 0..total_nodes as u32 {
            key_shares.insert(
                i,
                FrostKeyShare {
                    node_id: i,
                    secret_share: secret_shares[&i],
                    public_key: group_public,
                    verification_keys: verification_keys.clone(),
                },
            );
        }

        (group_public, key_shares)
    }

    /// Sign a message using a node's secret share
    pub fn sign(msg: &[u8], key_share: &FrostKeyShare) -> SignatureShare {
        // Deterministic Hash to G1 (Simplified for architecture context)
        let mut msg_hash = [0u8; 32];
        let len = msg.len().min(32);
        msg_hash[..len].copy_from_slice(&msg[..len]);
        
        let mut bytes = [0u8; 64];
        bytes[..32].copy_from_slice(&msg_hash);
        let h = G1Projective::generator() * Scalar::from_bytes_wide(&bytes);

        SignatureShare {
            node_id: key_share.node_id,
            share: h * key_share.secret_share,
        }
    }

    /// Aggregate signature shares into a valid group signature using Lagrange interpolation
    pub fn aggregate(
        shares: &[SignatureShare],
        threshold: usize,
    ) -> Result<G1Projective, &'static str> {
        if shares.len() < threshold {
            return Err("Not enough shares to aggregate");
        }

        let mut aggregated_sig = G1Projective::identity();
        let subset = &shares[0..threshold];

        for i in 0..threshold {
            let mut num = Scalar::one();
            let mut den = Scalar::one();
            let x_i = Scalar::from((subset[i].node_id + 1) as u64);

            for j in 0..threshold {
                if i == j {
                    continue;
                }
                let x_j = Scalar::from((subset[j].node_id + 1) as u64);

                num *= x_j;
                den *= x_j - x_i;
            }

            let den_inv = den.invert().unwrap(); // denominator is never zero since IDs are unique
            let lagrange_coeff = num * den_inv;

            aggregated_sig += subset[i].share * lagrange_coeff;
        }

        Ok(aggregated_sig)
    }

    /// Verify an aggregated group signature
    pub fn verify_group_signature(
        msg: &[u8],
        signature: &G1Projective,
        group_public_key: &G2Projective,
    ) -> bool {
        let mut msg_hash = [0u8; 32];
        let len = msg.len().min(32);
        msg_hash[..len].copy_from_slice(&msg[..len]);
        
        let mut bytes = [0u8; 64];
        bytes[..32].copy_from_slice(&msg_hash);
        let h = G1Projective::generator() * Scalar::from_bytes_wide(&bytes);

        let pairing_sig = bls12_381::pairing(&signature.to_affine(), &G2Projective::generator().to_affine());
        let pairing_msg = bls12_381::pairing(&h.to_affine(), &group_public_key.to_affine());

        pairing_sig == pairing_msg
    }
}
